---
title: "LeafDamage"
author: "Gabriella Altmire"
date: "6/15/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse) 
library(dplyr)
library(ggplot2)
library(deSolve)
library(ggsignif)
library(lme4)
library(car)
library(ggpubr)
library(reshape2)
library(nlme)
library(piecewiseSEM)
library(multcompView)

## read in data
leafdamage <- read_csv("LD2021_bromus_lupine.csv") 
rings <- read_csv("RCs2021.csv")
cnratios <- read_csv("cndata2021.csv")
coverBL <- read_csv("cover2021_bromus_lupine.csv")
coverALL <- read_csv("cover2021_all.csv")
biomass <- read_csv("Biomass2021.csv")
structure <- read_csv("PlantStructure2021.csv")

## SE function
calcSE<-function(x){
  x <- x[is.na(x)==F]
  sd(x)/sqrt(length(x))
}
```

## Combining into one dataset

```{r combine}
## leaf damage - per capita
leafdamageclean <- leafdamage %>%
  select(Block, Plot, N, P, K, Treatment, Species, Chewing) %>%
  na.omit(Chewing)%>%
  group_by(Block, Plot, N, P, K, Treatment, Species)%>%
  summarize(mean= mean(Chewing), SE = calcSE(Chewing))

leafd <- dcast(leafdamageclean, Block + Plot + N + P + K + Treatment~Species)

ringsclean <- rings %>%
  select(Block, Plot, N, P, K, Treatment, Count)%>%
  group_by(Plot)%>%
  mutate(total = Count * 25)%>%
  summarize(mean= mean(total), SE = calcSE(total))

ringsLD = merge(x=leafd, y=ringsclean, by="Plot", all.x= TRUE)
ringsLD <- ringsLD %>%
  rename("BmeanLD" = "Bromus", "LmeanLD" = "Lupine", "HOPPERmean" = "mean", "HOPPERse" = "SE")

##NA's for BmeanLD mean no bromus was in those plots; hopper abundance not collected in H- plots

percN <- cnratios %>%
  select(Plot, Species, percN)

percNprepped <- dcast(percN, Plot~Species)
percNprepped <- percNprepped %>%
  rename("BpercN" = "Bromus", "LpercN" = "Lupine")

ringsLDpercN <- merge(x=ringsLD, y=percNprepped, by = "Plot", all.x=TRUE)

cover <- coverBL%>%
  select(Block, Plot, Treatment, N, P, K, Species, CoverExclosure, CoverControl, CoverNutMain) %>%
  drop_na(CoverExclosure, CoverControl)

# pivot longer to get all cover estimates in one column
pivotedcover <- cover %>%
  pivot_longer(
    cols = c("CoverExclosure", "CoverControl", "CoverNutMain"),
    names_to = "SubPlot",
    values_to = "PCover"
  )

covermeansP <- pivotedcover%>%
  group_by(Plot, Species)%>%
  summarize(mean = mean(PCover), SE = calcSE(PCover))

coverprepped <- dcast(covermeansP, Plot~Species)
coverprepped <- coverprepped %>%
  rename("BmeanCover" = "Bromus", "LmeanCover" = "Lupine")

ALLdata <- merge(x=ringsLDpercN, y=coverprepped, by = "Plot", all.x=TRUE)
```

## Including Plots

You can also embed plots, for example:

```{r SEM attempt}

AlldataNONA <- na.omit(ALLdata)

LDSEM <- psem(
  lme(BpercN ~ N, random = ~1|Block, data= AlldataNONA, method= "ML"),
  lme(BmeanCover ~ N, random = ~1|Block, data= AlldataNONA, method= "ML"),
  lme(BmeanLD ~ BpercN + BmeanCover + N, random = ~1|Block, data= AlldataNONA, method= "ML"), data=AlldataNONA
)

summary(LDSEM, .progressBar = FALSE)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
